/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Dao.NhanVienDao;
import Modell.TaiKhoan;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author Admin
 */
public class dangnhapne extends javax.swing.JFrame {

   
    private  List<TaiKhoan>taiKhoans;
    private  NhanVienDao  conTroller ;
    ImageIcon icon;
    public dangnhapne() {
        initComponents();
        setVisible(false);
        textpass.setBackground(new Color(0,0,0,0));
        user1.setBackground(new Color(0,0,0,0));
        user2.setBackground(new Color(0,0,0,0));
        jpass.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        disable.setVisible(false);
        conTroller=new NhanVienDao();
        taiKhoans=new ArrayList<>();
        icon = new ImageIcon("C:\\Users\\Admin\\Desktop\\QuanLyKaraoke1\\QuanLyKaraoke\\src\\View\\icon\\micneeee.png");
        setIconImage(icon.getImage());
        setTitle("Karaoke");
        try {
            taiKhoans=conTroller.Selecttaikhoan();
        } catch (SQLException ex) {
            Logger.getLogger(dangnhapne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jpass = new javax.swing.JPasswordField();
        textpass = new javax.swing.JTextField();
        user2 = new javax.swing.JTextField();
        user1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("ĐĂNG NHẬP");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 350, 270, 40);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SIGN IN");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 90, 350, 60);

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("THOÁT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 400, 270, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật Khẩu :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 260, 100, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(40, 230, 270, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(40, 320, 270, 10);

        jpass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jpass.setForeground(new java.awt.Color(255, 255, 255));
        jpass.setBorder(null);
        jpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpassMouseClicked(evt);
            }
        });
        jpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassActionPerformed(evt);
            }
        });
        jpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpassKeyTyped(evt);
            }
        });
        jPanel1.add(jpass);
        jpass.setBounds(40, 290, 170, 30);

        textpass.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        textpass.setForeground(new java.awt.Color(153, 153, 153));
        textpass.setText("Password");
        textpass.setBorder(null);
        textpass.setEnabled(false);
        textpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textpassMouseClicked(evt);
            }
        });
        textpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textpassKeyTyped(evt);
            }
        });
        jPanel1.add(textpass);
        textpass.setBounds(40, 290, 170, 30);

        user2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        user2.setForeground(new java.awt.Color(255, 255, 255));
        user2.setBorder(null);
        user2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user2MouseClicked(evt);
            }
        });
        user2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user2ActionPerformed(evt);
            }
        });
        user2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                user2KeyTyped(evt);
            }
        });
        jPanel1.add(user2);
        user2.setBounds(40, 200, 223, 30);

        user1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        user1.setForeground(new java.awt.Color(153, 153, 153));
        user1.setText("Username");
        user1.setBorder(null);
        user1.setEnabled(false);
        user1.setFocusable(false);
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1MouseClicked(evt);
            }
        });
        user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1ActionPerformed(evt);
            }
        });
        user1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                user1KeyTyped(evt);
            }
        });
        jPanel1.add(user1);
        user1.setBounds(40, 200, 223, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tài Khoản :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 170, 100, 20);

        show.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/1111.png"))); // NOI18N
        show.setToolTipText("");
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel1.add(show);
        show.setBounds(280, 300, 30, 20);

        disable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        disable.setForeground(new java.awt.Color(255, 255, 255));
        disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/222.png"))); // NOI18N
        disable.setToolTipText("");
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel1.add(disable);
        disable.setBounds(280, 300, 20, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/png-transparent-karaoke-music-logo-piano-bar-magazine-cover-design-text-logo-magenta-removebg-preview.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 10, 200, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/1 (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 360, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpassMouseClicked

    }//GEN-LAST:event_jpassMouseClicked

    private void textpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textpassMouseClicked
        jpass.setVisible(true);
        jpass.setEnabled(false);
    }//GEN-LAST:event_textpassMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void user1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseClicked
        user2.setVisible(true);
        user2.setEditable(false);
        
    }//GEN-LAST:event_user1MouseClicked

    private void user2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2MouseClicked

    }//GEN-LAST:event_user2MouseClicked

    private void user1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user1KeyTyped

    }//GEN-LAST:event_user1KeyTyped

    private void textpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textpassKeyTyped

    }//GEN-LAST:event_textpassKeyTyped

    private void user2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user2KeyTyped
        if("".equals(user2.getText())){
            user1.setVisible(true);
            user1.setEditable(false);
        }
        else{
            user1.setVisible(false);
            user1.setEditable(false);
        }
    }//GEN-LAST:event_user2KeyTyped

    private void jpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpassKeyTyped
        if("".equals(jpass.getText())){
            textpass.setVisible(true);
            textpass.setEditable(false);
        }
        else{
            
            textpass.setVisible(false);
            textpass.setEditable(false);
        }
    }//GEN-LAST:event_jpassKeyTyped

    private void user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1ActionPerformed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        disable.setVisible(true);
        disable.setEnabled(true);
        jpass.setEchoChar((char)0);
        show.setVisible(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setVisible(true);
        show.setEnabled(true);
        jpass.setEchoChar((char)1);
        
    }//GEN-LAST:event_disableMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int cout=0;
        for (int i = 0; i < taiKhoans.size(); i++) {
          if((user2.getText().equalsIgnoreCase(taiKhoans.get(i).getUse()))&&
                  (jpass.getText().equalsIgnoreCase(taiKhoans.get(i).getPass()))){
                   TrangChu trangChu =new TrangChu( taiKhoans.get(i));
                    trangChu.setLocationRelativeTo(null);
                   trangChu.setVisible(true);
                   cout++;
                   this.dispose();
                   break;
          }
        }
        if(cout==0){
            JOptionPane.showMessageDialog(rootPane, "Tài Khoản hoặc Mật Khẩu Không Đúng !");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered

    }//GEN-LAST:event_jButton2MouseEntered

    private void user2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user2ActionPerformed
    if(user2.getText().length()>0){
         if(jpass.getText().length()>0){
        int cout=0;
        for (int i = 0; i < taiKhoans.size(); i++) {
          if((user2.getText().equalsIgnoreCase(taiKhoans.get(i).getUse()))&&
                  (jpass.getText().equalsIgnoreCase(taiKhoans.get(i).getPass()))){
                   TrangChu trangChu =new TrangChu( taiKhoans.get(i));
                    trangChu.setLocationRelativeTo(null);
                   trangChu.setVisible(true);
                   cout++;
                   this.dispose();
                   break;
          }
        }
        if(cout==0){
            JOptionPane.showMessageDialog(rootPane, "Tài Khoản hoặc Mật Khẩu Không Đúng !");
        }
    } else{
             jpass.requestFocus();
         }
    
    }else{
             JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập tài khoản !");
             user2.requestFocus();
         }
    
    }//GEN-LAST:event_user2ActionPerformed

    private void jpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassActionPerformed
        // TODO add your handling code here:
         if(jpass.getText().length()>0){
         if(user2.getText().length()>0){
        int cout=0;
        for (int i = 0; i < taiKhoans.size(); i++) {
          if((user2.getText().equalsIgnoreCase(taiKhoans.get(i).getUse()))&&
                  (jpass.getText().equalsIgnoreCase(taiKhoans.get(i).getPass()))){
                   TrangChu trangChu =new TrangChu( taiKhoans.get(i));
                    trangChu.setLocationRelativeTo(null);
                   trangChu.setVisible(true);
                   cout++;
                   this.dispose();
                   break;
          }
        }
        if(cout==0){
            JOptionPane.showMessageDialog(rootPane, "Tài Khoản hoặc Mật Khẩu Không Đúng !");
        }
    } else{
             user2.requestFocus();
         }
    
    }else{
         JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mật khẩu !");
             jpass.requestFocus();
         } 
        
        
        
        
        
    }//GEN-LAST:event_jpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangnhapne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangnhapne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangnhapne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangnhapne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dangnhapne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel disable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JLabel show;
    private javax.swing.JTextField textpass;
    private javax.swing.JTextField user1;
    private javax.swing.JTextField user2;
    // End of variables declaration//GEN-END:variables
}
