/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modell.DichVu;
import java.sql.SQLException;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeCellEditor;

/**
 *
 * @author Admin
 */
public class Hoadon extends javax.swing.JFrame {

    /**
     * Creates new form Hoadon
     */
      private  List <DichVu> dichVusk=new ArrayList<>();
      private  Thanhtoan thanhtoan;
      private  TrangChu trangChu;
    public Hoadon(Thanhtoan thanhtoan, boolean modal,String dichVus, List<DichVu> dichVus1) {
      // super(parent, modal);
        initComponents();
         this.thanhtoan=  thanhtoan;
        setLocationRelativeTo(null);
           jTextArea1.setText(dichVus);
           this.dichVusk.addAll(dichVus1);
           showdata ();

    }

   public Hoadon(String dichVus, List<DichVu> dichVus1) {
        initComponents();
        setLocationRelativeTo(null);
           jTextArea1.setText(dichVus);
           this.dichVusk.addAll(dichVus1);
           showdata ();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        Thoát = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 461));

        jTabbedPane3.addTab("tab1", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên", "Sô lượng", "Giá", "Ngày đặt", "Tổng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setRowHeight(25);
        jTable5.setShowHorizontalLines(false);
        jTable5.setShowVerticalLines(false);
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable5);
        if (jTable5.getColumnModel().getColumnCount() > 0) {
            jTable5.getColumnModel().getColumn(0).setResizable(false);
            jTable5.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 63, -1, 390));

        Thoát.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        Thoát.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/exit_24px.png"))); // NOI18N
        Thoát.setText("Thoát");
        Thoát.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoátActionPerformed(evt);
            }
        });
        jPanel4.add(Thoát, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 10, 148, 43));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/12.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 470));

        jTabbedPane3.addTab("tab2", jPanel4);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 480, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
      int check =jTable5.getSelectedRow();
      Order order =new Order(this,dichVusk.get(check), check);
      order.jTabbedPane1.setSelectedIndex(2);
      order.setVisible(true);
    }//GEN-LAST:event_jTable5MouseClicked

    private void ThoátActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoátActionPerformed
        dispose();
    }//GEN-LAST:event_ThoátActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Thoát;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void showdata() {
               DefaultTableModel defaultTableModel =(DefaultTableModel) jTable5.getModel();
           defaultTableModel.setRowCount(0);
           int i=1;
           for (DichVu dichVu : dichVusk) {
            defaultTableModel.addRow(new Object[]{
             i++, dichVu.getTenDV(),dichVu.getSoluong(),dichVu.getGiaDV(),dichVu.getNgaydat(),dichVu.getSoluong()*dichVu.getGiaDV()
            });
        }
    }

 
 
     void AddDichvu(DichVu dichVu) {
       int cout = 0;
     for (int i = 0; i < dichVusk.size(); i++) {
            if (dichVusk.get(i).getID() == dichVu.getID()) {
                dichVu.setSoluong(dichVu.getSoluong() + dichVusk.get(i).getSoluong());
                cout++;
                break;
            }
        }
        if (cout == 0) {
            dichVusk.add(dichVu);
        }
      showdata();
    }

    void edit(DichVu dichVu, int check) {

        try {
            thanhtoan.edit(dichVu, check);
            dichVusk.remove(check);
            AddDichvu(dichVu);
        } catch (SQLException ex) {
            Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public  void delete(int check) {
            dichVusk.remove(check);
            showdata();
           thanhtoan.detele(check);
    }
 
}
