/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.NhanVienDao;
import Modell.NhanVien;
import Modell.TaiKhoan;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Taikhoan extends javax.swing.JDialog {

    /**
     * Creates new form Taikhoan
     */
    private  NhanVien nhanVien;
    private TrangChu trangChu;
    private  TaiKhoan taikhoan;
    public Taikhoan(java.awt.Frame parent, boolean modal,NhanVien nhanVien) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        trangChu =(TrangChu) parent;
        this.nhanVien=nhanVien;
        jTextField21.setText(nhanVien.getTen());
        
    }
     public Taikhoan(java.awt.Frame parent, boolean modal,TaiKhoan taiKhoan) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        trangChu =(TrangChu) parent;
        this.taikhoan=taiKhoan;
        jTextField22.setText(taiKhoan.getUse());
        jPasswordField5.setText(taiKhoan.getPass());
     
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aa = new javax.swing.JTabbedPane();
        jPanel61 = new javax.swing.JPanel();
        jPanel63 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel62 = new javax.swing.JPanel();
        jPanel64 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPasswordField5 = new javax.swing.JPasswordField();
        jLabel87 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel63.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel81.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel81.setText("Tên Đăng Nhập :");
        jPanel63.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel82.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel82.setText("Mật Khẩu:");
        jPanel63.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        jTextField21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel63.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, -1));

        jLabel83.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel83.setText("Xác Nhận :");
        jPanel63.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 30));

        jButton21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/checkmark_26px.png"))); // NOI18N
        jButton21.setText("XÁC NHẬN");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel63.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 166, 40));

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel63.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 230, -1));

        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel63.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TẠO TÀI KHOẢN");
        jPanel63.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 400, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/12.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel63.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 390, 380));

        javax.swing.GroupLayout jPanel61Layout = new javax.swing.GroupLayout(jPanel61);
        jPanel61.setLayout(jPanel61Layout);
        jPanel61Layout.setHorizontalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel61Layout.createSequentialGroup()
                .addComponent(jPanel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel61Layout.setVerticalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel61Layout.createSequentialGroup()
                .addComponent(jPanel63, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        aa.addTab("tab1", jPanel61);

        jPanel64.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel84.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel84.setText("Tên Đăng Nhập");
        jPanel64.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 114, 19));

        jLabel85.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel85.setText("Mật khẩu mới :");
        jPanel64.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 114, -1));

        jTextField22.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextField22.setText("jTextField21");
        jPanel64.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 202, -1));

        jLabel86.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel86.setText("Xác nhận:");
        jPanel64.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 114, -1));

        jButton22.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton22.setText("ĐỔI");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel64.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 132, -1));

        jPasswordField3.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPasswordField3.setEnabled(false);
        jPanel64.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 200, -1));

        jPasswordField4.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPasswordField4.setEnabled(false);
        jPanel64.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 200, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel64.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, -1));

        jPasswordField5.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPasswordField5.setText("jPasswordField1");
        jPasswordField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField5ActionPerformed(evt);
            }
        });
        jPanel64.add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 200, -1));

        jLabel87.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel87.setText("Mật khẩu Cũ :");
        jPanel64.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 114, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ĐỔI MẬT KHẨU");
        jPanel64.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 400, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/12.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel64.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 340));

        javax.swing.GroupLayout jPanel62Layout = new javax.swing.GroupLayout(jPanel62);
        jPanel62.setLayout(jPanel62Layout);
        jPanel62Layout.setHorizontalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel62Layout.createSequentialGroup()
                .addComponent(jPanel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel62Layout.setVerticalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel64, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        aa.addTab("tab2", jPanel62);

        getContentPane().add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -26, -1, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
      boolean check=true;
        if(jTextField21.getText().length()==0){
          JOptionPane.showMessageDialog(rootPane,"Bạn vui lòng nhập tên đăng nhập ");
        check=false;
        
      }
          if(jPasswordField1.getText().length()==0){
          JOptionPane.showMessageDialog(rootPane,"Bạn vui lòng nhập mật khẩu ");
        check=false;
        
      }
          String pass1=jPasswordField1.getText();
          String pass2=jPasswordField1.getText();
     if(!pass1.equals(pass2)) {
         JOptionPane.showMessageDialog(rootPane,"Mật khẩu nhập vào không trùng khớp ");
         check=false;
     }
        if (check==true) {
            TaiKhoan taiKhoan =new TaiKhoan(nhanVien.getID(),jTextField21.getText(),jPasswordField1.getText(), nhanVien.getChucVu());
            trangChu.addTaikhoan(taiKhoan);
            this.dispose();
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
     NhanVienDao nhanVienDao=new NhanVienDao();
        boolean check=true;
        if(jTextField22.getText().length()==0){
          JOptionPane.showMessageDialog(rootPane,"Bạn vui long nhập tên đăng nhập ");
        check=false;
        
      }
          if(jPasswordField3.getText().length()==0){
          JOptionPane.showMessageDialog(rootPane,"Bạn vui lòng nhập mật khẩu ");
        check=false;
        
      }
     if(!jPasswordField4.getText().equalsIgnoreCase(jPasswordField3.getText())) {
         JOptionPane.showMessageDialog(rootPane,"Mật khẩu nhập vào không trùng khớp ");
         check=false;
     }
        if (check==true) {
            TaiKhoan taiKhoan =new TaiKhoan(taikhoan.getID(),jTextField22.getText(),jPasswordField3.getText(), taikhoan.getPhanquyen());
           try {
             nhanVienDao.Delete(this.taikhoan);
            nhanVienDao.InsertInto(taiKhoan);
               trangChu.Loandatase();
               JOptionPane.showMessageDialog(rootPane,"Thay đổi thành công ");
           } catch (SQLException ex) {
               Logger.getLogger(Taikhoan.class.getName()).log(Level.SEVERE, null, ex);
           }
            this.dispose();
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField5ActionPerformed
      if(jPasswordField5.getText().equalsIgnoreCase(taikhoan.getPass())){
       jPasswordField3.setEnabled(true);
       jPasswordField4.setEnabled(true);
      }
      else{
       jPasswordField3.setEnabled(false);jPasswordField4.setEnabled(false);
      }
    }//GEN-LAST:event_jPasswordField5ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane aa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    // End of variables declaration//GEN-END:variables
}
