/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modell.Datphong;
import Modell.DichVu;
import Modell.HoaDon;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Thanhtoan extends javax.swing.JFrame{

   private  int Tongtien=0;
    public TrangChu  trangChu;
    private  int thanhtoan;
    public Thanhtoan(java.awt.Frame parent, boolean modal ,int thanhtoan) {
        //super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
       trangChu=(TrangChu) parent;
       this.thanhtoan =thanhtoan;
       Showm(trangChu.datphongs.get(thanhtoan));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jButton36 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jButton38 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel42.setBackground(new java.awt.Color(0, 204, 204));

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Thanh Toán - Trả Phòng");

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel45.setBackground(new java.awt.Color(0, 204, 204));
        jPanel45.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Hóa Đơn Karaoke", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel49.setText("Tên Phòng :");
        jPanel45.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 48, 97, -1));

        jTextField17.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 45, 183, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel50.setText("Loại Phòng :");
        jPanel45.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 94, 97, -1));

        jTextField18.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 91, 183, -1));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel51.setText("giá Phòng/1h :");
        jPanel45.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 144, -1, -1));

        jTextField19.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 141, 183, -1));

        jTextField20.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 188, 183, -1));

        jTextField21.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 236, 183, -1));

        jLabel54.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel54.setText("Giờ Đến :");
        jPanel45.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 289, 94, -1));

        jTextField22.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 286, 185, -1));

        jLabel55.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel55.setText("Giờ Trả :");
        jPanel45.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 339, 94, -1));

        jTextField23.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 336, 185, -1));

        jLabel56.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel56.setText("Số Giờ :");
        jPanel45.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 392, 80, -1));

        jTextField24.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 389, 186, -1));

        jLabel57.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel57.setText("Tiền Phòng :");
        jPanel45.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 445, -1, -1));

        jTextField25.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel45.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 442, 186, -1));

        jLabel58.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel58.setText("Ngày DV :");
        jPanel45.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 48, 204, -1));

        jTextField26.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 45, 226, -1));

        jLabel59.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel59.setText("Số DV :");
        jPanel45.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 94, 75, -1));

        jTextField27.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 91, 226, -1));

        jLabel60.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel60.setText("Tiền DV :");
        jPanel45.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 139, 73, -1));

        jTextField28.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel45.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 136, 226, -1));

        jLabel61.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel61.setText("NV PVụ :");
        jPanel45.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 261, 74, -1));

        jTextField29.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel45.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 258, 223, -1));

        jButton36.setBackground(new java.awt.Color(204, 204, 204));
        jButton36.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/add.png"))); // NOI18N
        jButton36.setText("THANH TOÁN");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel45.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 426, 225, 43));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel17.setText("TỔNG TIỀN THANH TOÁN");
        jPanel45.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 339, -1, -1));

        jLabel62.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel62.setText("0 VNĐ");
        jPanel45.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 395, 129, -1));

        jButton38.setBackground(new java.awt.Color(255, 255, 204));
        jButton38.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton38.setText("Xem dịch vụ");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel45.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 188, 157, 27));

        jLabel64.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel64.setText("Ngày Trả :");
        jPanel45.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 239, 97, -1));

        jLabel65.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel65.setText("Ngày Đến :");
        jPanel45.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 191, 97, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/12.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel45.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 670, 500));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed

        try {
            if (trangChu.datphongs.get(thanhtoan).getDichVus().size() > 0) {

                Hoadon hoadon = new Hoadon(this, rootPaneCheckingEnabled, trangChu.datphongs.get(thanhtoan).toString(), trangChu.datphongs.get(thanhtoan).getDichVus());
                hoadon.jTabbedPane3.setSelectedIndex(1);
                hoadon.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed

        for (int i = 0; i < trangChu.phongs.size(); i++) {
            if (trangChu.phongs.get(i).getMaphong().equals(trangChu.datphongs.get(thanhtoan).getPhong().getMaphong())) {
                trangChu.phongs.get(i).setTinhtrang("Đang trống");
                try {
                    Hoadon hoadon = new Hoadon( trangChu.datphongs.get(thanhtoan).toString(), trangChu.datphongs.get(thanhtoan).getDichVus());
                    hoadon.jTabbedPane3.setSelectedIndex(0);
                    hoadon.setVisible(true);
                    String ngay =LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                    HoaDon lichsu =new HoaDon(trangChu.datphongs.get(thanhtoan), ngay,Tongtien );
                    trangChu.hoaDonDao.InsertInto(lichsu);
                    trangChu.phongDao.Update(trangChu.phongs.get(i));
                    for (DichVu dichVu :(TrangChu.datphongs.get(thanhtoan).getDichVus())) {
                        trangChu.datPhogDao.delete(dichVu,trangChu.datphongs.get(thanhtoan).getKhachHang().getCMND());
                    }
                    trangChu.datPhogDao.Delete(trangChu.datphongs.get(thanhtoan));
                    trangChu.Loandatase();
                } catch (SQLException ex) {
                    Logger.getLogger(Thanhtoan.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;

            }
        }

        dispose();
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton38;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    // End of variables declaration//GEN-END:variables

    public void Showm(Datphong datphong) {
        jTextField17.setText(datphong.getPhong().getTenphong());
        jTextField18.setText(datphong.getPhong().getLoaiphonh());
        jTextField19.setText(datphong.getPhong().getGiaphong() + "");
        jTextField20.setText(datphong.getNgaydat().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
        LocalDateTime localDateTime = LocalDateTime.now();
        jTextField21.setText(localDateTime.format(DateTimeFormatter.ISO_DATE));
        jTextField22.setText(datphong.getNgaydat().format(DateTimeFormatter.ofPattern("hh:mm a")));
        jTextField23.setText(localDateTime.format(DateTimeFormatter.ofPattern("hh:mm a")));
        int sum = 0;
        int soluong = 0;

        for (int i = 0; i < trangChu.datphongs.get(thanhtoan).getDichVus().size(); i++) {
            sum += trangChu.datphongs.get(thanhtoan).getDichVus().get(i).getSoluong() * trangChu.datphongs.get(thanhtoan).getDichVus().get(i).getGiaDV();
            soluong += trangChu.datphongs.get(thanhtoan).getDichVus().get(i).getSoluong();
        }
        jTextField26.setText(trangChu.datphongs.get(thanhtoan).getNgaydatdichvu());
        jTextField27.setText(soluong + "");
        jTextField28.setText(sum + "");
        jTextField29.setText(trangChu.datphongs.get(thanhtoan).getNhanVien().getTen());
        int phutHienTai = localDateTime.getHour() * 60 + localDateTime.getMinute();
        int gio = (phutHienTai - ((trangChu.datphongs.get(thanhtoan).getNgaydat().getHour() * 60) + (trangChu.datphongs.get(thanhtoan).getNgaydat().getMinute()))) / 60;
        float du = (phutHienTai - ((trangChu.datphongs.get(thanhtoan).getNgaydat().getHour() * 60) + (trangChu.datphongs.get(thanhtoan).getNgaydat().getMinute()))) % 60;
        if (du >= 30) {
            du = 1;
        } else {
            du = 0;
        }
        jTextField24.setText(gio + du + "");
        jTextField25.setText(trangChu.datphongs.get(thanhtoan).getPhong().getGiaphong() + "VND");
         Tongtien = (int) ((trangChu.datphongs.get(thanhtoan).getPhong().getGiaphong() * (gio + du))) + sum;
        jLabel62.setText(Tongtien + "VND");
    
    }

    public  void detele(int check) {
  
       try {
           trangChu.datPhogDao.delete(trangChu.datphongs.get(thanhtoan).getDichVus().get(check),trangChu.datphongs.get(thanhtoan).getKhachHang().getCMND());
           trangChu.Loandatase();
       } catch (SQLException ex) {
           Logger.getLogger(Thanhtoan.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        Showm(trangChu.datphongs.get(thanhtoan));
    }

    public  void edit(DichVu dichvu,int check) throws SQLException {
      trangChu.datPhogDao.Updatedatdichvu(trangChu.datphongs.get(thanhtoan).getDichVus().get(check),trangChu.datphongs.get(thanhtoan).getKhachHang().getCMND());
      trangChu.Loandatase();
     Showm(trangChu.datphongs.get(thanhtoan));
    }
}
